name: Build app
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm i -g create-elm-app
      - run: npm ci
      - run: npm run build
